version: "3"
services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "4040:5432"
  client:
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  server:
    restart: always
    build: ./server
    ports: "4000:4000"
    volumes:
      - ./server:/app
    depends_on:
      - postgresdb
