version: "3"
services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school
    ports:
      - "5432:5432"
  client:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
